### PR TITLE
8 likes

### PR DESCRIPTION
**Pull request by camille-seguette**
It's telling me I can't automatically merge, but that I can still create the pull request...

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
@camille-seguette follow the instructions above (click open the "Use the command line" instructions) to merge it yourself. I approve!

**Comment by camille-seguette** [comment]
Okay, so when I type "git checkout -b 8-likes origin/8-likes" it tells me that the branch already exists, bc it does obviously, so if I type it without the "-b" it says it doesn't match any files known to git... 

Camilles-MBP:blocmarks camille$ git fetch origin
Camilles-MBP:blocmarks camille$ git checkout -b 8-likes origin/8-likes
fatal: A branch named '8-likes' already exists.
Camilles-MBP:blocmarks camille$ git checkout 8-likes origin/8-likes
error: pathspec 'origin/8-likes' did not match any file(s) known to git.

**Comment by brittanyjspringer** [comment]
@camille-seguette do this: 

    $ git checkout -D 8-likes origin/8-likes

Then checkout with the new branch

**Comment by camille-seguette** [comment]
Getting this:
Camilles-MBP:blocmarks camille$ git checkout -D 8-likes origin/8-likes
error: unknown switch `D'
usage: git checkout [<options>] <branch>
   or: git checkout [<options>] [<branch>] -- <file>...

When you say "then checkout with the new branch" do you mean the branch I created for checkpoint 9?

**Comment by brittanyjspringer** [comment]
I missed a word!

    $ git branch -D 8-likes origin/8-likes

branch, not checkout :)

**Comment by camille-seguette** [comment]
Camilles-MBP:blocmarks camille$ git branch -D 8-likes origin/8-likes
Deleted branch 8-likes (was aee390e).
error: branch 'origin/8-likes' not found.

Is this right? Looks scary...

**Comment by brittanyjspringer** [comment]
That is right! Now go through the steps.

**Comment by camille-seguette** [comment]
Just want to make sure this is correct before I proceed:

Camilles-MBP:blocmarks camille$ git branch -D 8-likes origin/8-likes
Deleted branch 8-likes (was aee390e).
error: branch 'origin/8-likes' not found.
Camilles-MBP:blocmarks camille$ git merge master
Already up-to-date.
Camilles-MBP:blocmarks camille$ git checkout master
Already on 'master'
Camilles-MBP:blocmarks camille$ git merge --no-ff 8-likes
merge: 8-likes - not something we can merge

Did you mean this?
	origin/8-likes

--- Should I type it as origin/8-likes?

**Comment by brittanyjspringer** [comment]
Try this: 

git checkout master
git pull origin master
git checkout -b 8-likes origin/8-likes
git pull origin 8-likes
git merge master
(fix the code)
git add .
git commit -m 'Resolve merge conflict'
git push

**Comment by camille-seguette** [comment]
When I type "git pull origin master" I'm getting this:

Camilles-MBP:blocmarks camille$ git checkout master
Already on 'master'
Camilles-MBP:blocmarks camille$ git pull origin master
From https://github.com/camille-seguette/blocmarks
 * branch            master     -> FETCH_HEAD
Auto-merging app/policies/application_policy.rb
CONFLICT (add/add): Merge conflict in app/policies/application_policy.rb
Auto-merging app/controllers/bookmarks_controller.rb
Auto-merging app/controllers/application_controller.rb
Auto-merging Gemfile
Automatic merge failed; fix conflicts and then commit the result.

Also, what code do I need to fix? I'm confused about what happened here; why was there a conflict in the first place?

**Comment by brittanyjspringer** [comment]
You need to open application_policy.rb and fix any junk that was added by Git. Basically, you adjusted application_policy.rb differently in Master and your Likes branch. Merge conflicts happen all the time, you need to learn how to fix them 💪

**Comment by camille-seguette** [comment]
Okay, so I think it should be good now...

**Comment by camille-seguette** [comment]
Although, I'm not sure what's up with this list of conflicting files now... Is that new?

**Comment by brittanyjspringer** [comment]
Yikes. That is bad. I'm stepping in now. @camille-seguette

**Comment by camille-seguette** [comment]
Omg, I'm sorry; I have no idea what's going on.

**Comment by brittanyjspringer** [comment]
@camille-seguette All good! I fixed it by patching the ApplicationPolicy. Merging and checking you off!

**Comment by camille-seguette** [comment]
Ahhh thank you so much!!!

**Pull request merged**
